version: '3.8'

services:
  identity_example.db:
    image: postgres
    restart: on-failure
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Password123
        - POSTGRES_DB=identity_example
    volumes:
        - identity_example_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 10s
      interval: 5s
      retries: 10
volumes:
    identity_example_data: null